### ISSUE TITLE
SNICS Business Partner due for Renewal

### ISSUE THREAD

**Issue by mirellasprenger** [springernature/snics-employee#195]
Email sent on Tue 26-Feb-19 5:59 PM:

Hi all, 

Carlos got the following email when his partner was due for renewal, which is good (it was correct) - however, when he clicked on the link the status of the partner in SNICS is still 'completed'  I think this is because the renewal wasn’t due for another 3 months but I wanted to double check at what date the ‘Expired’ status would kick in? (and could we ask Anne-Laure to double check it is working?)

Thanks
Steph

![error](https://user-images.githubusercontent.com/43644896/53561290-ba43bc80-3b4e-11e9-81e2-99d96f7eba23.png)

**Comment by mirellasprenger** [comment]
Updating with the new email sent on Fri 01-Mar-19 12:48 PM that might be related.

![image](https://user-images.githubusercontent.com/43644896/53723420-0735d480-3e68-11e9-8181-ad53d1f451ec.png)

**Comment by mirellasprenger** [comment]
Check with Siddiqui if it is possible to check who answered the questionnaire.

**Comment by karentom** [comment]
@mirellasprenger Second email is a different issue. I had created a new ticket for this.

**Comment by karentom** [comment]
@harshadporwal I tried to test the issue that Steph mentioned in the email and ran ZSNICS_RENEWAL_REMINDER in MQS and I could not get the status to change from Reviewed to Expired. We need to find out why this is not working.

**Comment by harshadporwal** [comment]
@karentom what is the ticket number for 2nd email as you mentioned in the above comment. The issue is fixed but I didn't find the ticket in Github.

**Comment by karentom** [comment]
I will discuss with Steph and get back to you.

**Comment by karentom** [comment]
@harshadporwal Below are the scenarios we need to consider:

1.	Contract will expire in 90 days and risk assessment will be more than 6 months old at the time of contract expiry.
-	An email will go out to the internal owner informing them that the contract will expire.
-	At that time, the system will check if the risk assessment is more than 3 months old. If it is, it will update the renewal date of the risk assessment to match the renewal date of the contract. This will trigger another email informing the internal owner that the risk assessment is due to expire.

2.	Contract will expire in 90 days and risk assessment will be less than 6 months old at the time of contract expiry. OK
-	An email will go out to the internal owner informing them that the contract will expire.
-	Nothing needs to happen for the risk assessment

3.	Risk assessment expires in 90 days (irrespective of whether there is a contract or not or when it is due to expire). 
-	An email will go out to the internal owner informing them that the risk assessment will expire.

Email text:
Dear Colleague,
    
Your Business Partner below is due for renewal in the SNICS system
    
https://snics-employee-live.springernature.app/#/partner_details/653 _**This link is dynamic.**_

Please review this Business Partner and update their risk assessment questionnaire / contract as required.

NB: When you come to renew the contract with your Business Partner the risk assessment questionnaire must be less than 6 months old, or it will require updating. Therefore you may wish to consider renewing the contract with your Business Partner now, to avoid having to redo the risk assessment questionnaire again if your contract is due for renewal in the next 9 months or less. 
    
For support please contact your Regional Compliance Officer or snics@springernature.com.
    
Kind regards,
SNICS

**Comment by harshadporwal** [comment]
@karentom I didnt get the requirment from the above. Need more clarification. If possible can you please schedule a call?

**Comment by karentom** [comment]
@harshadporwal Status should be set to 'Expired' when the renewal for the assessment expires. 

In the example below, the status will change to 'Expired' on 03/19/2019.

![image](https://user-images.githubusercontent.com/17595871/55085523-31e90680-507d-11e9-9b00-163a3df8aaa0.png)

**Comment by karentom** [comment]
@harshadporwal - I cannot get an email to trigger for renewal. I had set the renewal date of the assessment to be 90 days from today (April 27th) but it is not working. I cannot get an email sent to me. I even changed the date to a day earlier and later to see if I was off, but still no luck. Can you please check what the issue is?

**Comment by harshadporwal** [comment]
@karentom Hopefully, I have fixed the ZSNICS_RENEWAL_REMINDER program and its available for testing in MQS. Only the language translation is not updated as I am waiting for translated text. 

If the expiry date is 90 days from today then it will trigger a mail tommorrow. So if you are testing please set a date 89 days from now so that mail is triggered. And also the status will get updated to 'Expired' after the expiry date passed. Let me know if any issues are found.

**Comment by karentom** [comment]
@harshadporwal 

I ran ZSNICS_RENEWAL_REMINDER and got 3 emails. They were for partner ids 1005 and 1014. I was only expecting one for 1014 because it was due for renewal in 90 days. 1005 was due March 19, 2019.

Can we also set it as 90 days, not 89?

Changing to 'Expired' status seems to be working.

Can you please change the recipient of these emails in UAT to be you, me, Steph, and Mirella? I had to notify a bunch of people in the business to ignore the emails that went out due to my testing. They were all sent because these were all internal emails. I will continue testing this ticket after this is done. I don't want to have to go through changing the email for all these assessments.

**Comment by harshadporwal** [comment]
@karentom I have made some more changes. Please test now.
The days is 90 only.
I have added recipents as you mentioned for UAT and DEV.
Added language translation for the email also

**Comment by karentom** [comment]
@harshadporwal Tested all 3 scenarios. Looks good.

**Comment by harshadporwal** [comment]
@karentom As the testing is completed, Can we move the progam to MPS?
